#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu26-e2e
    username: tester
    # Test password: 1
    password: "$6$E92PuETYpIsDM7DN$4mbBr.3WJkZIA23HPuAVb3crjVK5Ak8Le7ndCQ3fhZQjNDD4O3pWjzc7p46/FUbhl1Nv/yHoyA68lA/GtmwIf/"
  refresh-installer:
    update: false
  source:
    search_drivers: false
    id: ubuntu-server
  network:
    version: 2
    ethernets: {}
  apt:
    geoip: false
  ssh:
    install-server: true
    authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDR5fzbzCT3fCaKzDP7chcvlD79p8Fw04l0g5ZjCZ9sMmJHfey1NDwXmX+isejuA7gM+fZd2T7jqm0S2KTLTzWzVCs3LlSsl2iHsoWtBikxGozYPbFgJ1lYsH3Qp2DMmjX+zQZUbmhRcOGXrkm2m9BKQjeWViMzy/vKERU0FGOCs0Rhl9CAOcevc47RMMWVcKgH21dK4s/mTXRwtk0ROTvpNYDnesuI4SmUAphZ0QtJOg9luhxlh4ENOWcegAeD5aOg2i+3CaufC4b+zfISRXoL2eOHTGtPyyFY9GMsahSe5I5sSOei8VrBUwiAadMMJdBwEd+6GOytFChVRbcmzLnHkBgkbjyuRicsPYUDTd/yUmNYU0HA88GWxRy8bMza1LoD0B2U5pFfho7pWykzgVRiEqws8hjxAP8ToxeLm5NBC1MqswENowXrNg+i9Qae+lLgs8RghbkPLpa0If3jqNJSuS9VlY6ZcCEML5Eno41XfK3jv6nZ3VWv64RMZPZZjm3+bWAU4J/2zZVRZN2cJMtWS/WRnc8RSYCA+1/KLUVOKvhkZOngNHin2/5Yfdr3v4PU5p58aQGxtmDR6Rc8gLSsaV307MV3eLbjYEtzS8PE41/3kp2/YIEJYWIbPUjGFoA+smam2YJ4x7tVVVtmoNMUuelSxOeGypwb+TeUC1PWWQ== tester@example
    allow-pw: true
  timezone: "Asia/Tehran"
  locale: en_US.UTF-8
  keyboard:
    layout: us
  storage:
    config:
      - id: disk0
        type: disk
        match:
          size: largest
        ptable: gpt
        wipe: superblock-recursive
        preserve: false
        grub_device: true
      - id: part-bios
        type: partition
        device: disk0
        size: 1M
        flag: bios_grub
      - id: part-boot
        type: partition
        device: disk0
        size: 1G
        flag: boot
      - id: part-lvm
        type: partition
        device: disk0
        size: -1
      - id: vg-os
        type: lvm_volgroup
        name: os
        devices: [part-lvm]
      - id: lv-root
        type: lvm_partition
        name: root
        volgroup: vg-os
        size: 7G
      - id: lv-var
        type: lvm_partition
        name: var
        volgroup: vg-os
        size: -1
      - id: fs-boot
        type: format
        volume: part-boot
        fstype: ext4
      - id: fs-root
        type: format
        volume: lv-root
        fstype: ext4
      - id: fs-var
        type: format
        volume: lv-var
        fstype: ext4
      - id: mount-boot
        type: mount
        device: fs-boot
        path: /boot
      - id: mount-root
        type: mount
        device: fs-root
        path: /
      - id: mount-var
        type: mount
        device: fs-var
        path: /var
